"""
Tensor Builder (Execution Models)
=================================
Aggregates the individual brick tensors generated by the sim_label_generator
and builds the final Train, Val, and Test massive numpy arrays for training.

Splits:
- Train: 2020-01-01 to 2025-06-30
- Val: 2025-07-01 to 2025-12-31
- Test: 2026-01-01 to Present
"""

import os
import glob
import time
import logging
import argparse
import numpy as np
import pandas as pd
from pathlib import Path

# ── Paths ────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent
LABELS_DIR = BASE_DIR / "outputs" / "sim_labels"
TENSOR_DIR = LABELS_DIR / "tensors"

OUTPUT_DIR = BASE_DIR / "outputs" / "exec_tensors"

logger = logging.getLogger(__name__)

# ── Split Boundaries ─────────────────────────────────────────────
TRAIN_END = pd.Timestamp("2025-06-30 23:59:59", tz="UTC")
VAL_END   = pd.Timestamp("2025-12-31 23:59:59", tz="UTC")


def sequence_to_array(seq_str: str) -> np.ndarray:
    """Converts a binary sequence string '10110...' into a float32 array (left-padded)."""
    arr = np.zeros(100, dtype=np.float32)
    # The newest brick is at the end of the string.
    # We place it at the end of the array (index 99) for consistent CNN spatial alignment.
    seq_str = seq_str[-100:]
    start_idx = 100 - len(seq_str)
    
    for i, char in enumerate(seq_str):
        if char == '1':
            arr[start_idx + i] = 1.0
        elif char == '0':
            arr[start_idx + i] = -1.0  # -1.0 for DOWN to distinguish from 0.0 padding!
            
    return arr


def build_split(split_name: str, df: pd.DataFrame):
    logger.info(f"Building {split_name} split with {len(df):,} samples...")
    
    n_samples = len(df)
    
    # Pre-allocate massive arrays
    X_micro = np.zeros((n_samples, 100, 9), dtype=np.float32)
    X_macro = np.zeros((n_samples, 3), dtype=np.float32)
    X_seq = np.zeros((n_samples, 100), dtype=np.float32)
    
    y_class = np.zeros((n_samples, 1), dtype=np.float32)
    y_mag = np.zeros((n_samples, 1), dtype=np.float32)
    
    valid_count = 0
    missing = 0
    
    t_start = time.time()
    for i, row in enumerate(df.itertuples()):
        b_id = row.brick_id
        year = getattr(row, 'year', None)
        
        if year is not None:
            micro_path = TENSOR_DIR / f"micro_{year}_{b_id}.npy"
            macro_path = TENSOR_DIR / f"macro_{year}_{b_id}.npy"
            seq_path = TENSOR_DIR / f"seq_{year}_{b_id}.txt"
        else:
            micro_path = TENSOR_DIR / f"micro_{b_id}.npy"
            macro_path = TENSOR_DIR / f"macro_{b_id}.npy"
            seq_path = TENSOR_DIR / f"seq_{b_id}.txt"
        
        if not (micro_path.exists() and macro_path.exists() and seq_path.exists()):
            missing += 1
            continue
            
        try:
            # Load
            micro = np.load(micro_path)
            macro = np.load(macro_path)
            with open(seq_path, 'r') as f:
                seq_str = f.read().strip()
                
            # Assign
            X_micro[valid_count] = micro
            X_macro[valid_count] = macro
            X_seq[valid_count] = sequence_to_array(seq_str)
            
            y_class[valid_count, 0] = row.y_class
            y_mag[valid_count, 0] = row.y_mag
            
            valid_count += 1
            
        except Exception as e:
            logger.error(f"Error loading brick {b_id}: {e}")
            missing += 1
            
        if (i + 1) % 10000 == 0:
            logger.info(f"  Processed {i+1}/{n_samples}...")
            
    logger.info(f"Completed {split_name}: {valid_count} valid, {missing} missing. Time: {time.time()-t_start:.1f}s")
    
    # Truncate to valid rows
    X_micro = X_micro[:valid_count]
    X_macro = X_macro[:valid_count]
    X_seq = X_seq[:valid_count]
    y_class = y_class[:valid_count]
    y_mag = y_mag[:valid_count]
    
    # Save
    np.save(OUTPUT_DIR / f"{split_name}_micro.npy", X_micro)
    np.save(OUTPUT_DIR / f"{split_name}_macro.npy", X_macro)
    np.save(OUTPUT_DIR / f"{split_name}_seq.npy", X_seq)
    np.save(OUTPUT_DIR / f"{split_name}_y_class.npy", y_class)
    np.save(OUTPUT_DIR / f"{split_name}_y_mag.npy", y_mag)
    
    logger.info(f"Saved {split_name} arrays to {OUTPUT_DIR}/")


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s"
    )
    
    logger.info("Loading all label parquets...")
    label_files = glob.glob(str(LABELS_DIR / "sim_labels_*.parquet"))
    
    if not label_files:
        logger.error(f"No label files found in {LABELS_DIR}")
        return
        
    dfs = [pd.read_parquet(f) for f in label_files]
    df = pd.concat(dfs, ignore_index=True)
    
    logger.info(f"Total labels loaded: {len(df):,}")
    
    # Sort by timestamp
    if 'utc_time' not in df.columns:
        df['utc_time'] = pd.to_datetime(df['timestamp'], unit='s', utc=True)
    df = df.sort_values('utc_time').reset_index(drop=True)
    
    # Mask splits
    train_mask = df['utc_time'] <= TRAIN_END
    val_mask = (df['utc_time'] > TRAIN_END) & (df['utc_time'] <= VAL_END)
    test_mask = df['utc_time'] > VAL_END
    
    df_train = df[train_mask]
    df_val = df[val_mask]
    df_test = df[test_mask]
    
    logger.info(f"Split sizes -> Train: {len(df_train):,}, Val: {len(df_val):,}, Test: {len(df_test):,}")
    
    build_split("train", df_train)
    build_split("val", df_val)
    build_split("test", df_test)
    
    logger.info("All tensors successfully built.")


if __name__ == "__main__":
    main()
