"""
Tensor Builder (Execution Models)
=================================
Aggregates the individual brick tensors generated by the sim_label_generator
and builds the final Train, Val, and Test massive numpy arrays for training.

Splits:
- Train: 2020-01-01 to 2025-06-30
- Val: 2025-07-01 to 2025-12-31
- Test: 2026-01-01 to Present
"""

import os
import glob
import time
import logging
import argparse
import numpy as np
import pandas as pd
from pathlib import Path
from collections import deque

# ── Paths ────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent
LABELS_DIR = BASE_DIR / "outputs" / "sim_labels"
TENSOR_DIR = LABELS_DIR / "tensors"

OUTPUT_DIR = BASE_DIR / "outputs" / "exec_tensors_regime"

logger = logging.getLogger(__name__)

# ── Split Boundaries ─────────────────────────────────────────────
TRAIN_END = pd.Timestamp("2025-06-30 23:59:59", tz="UTC")
VAL_END   = pd.Timestamp("2025-12-31 23:59:59", tz="UTC")


def sequence_to_array(seq_str: str) -> np.ndarray:
    """Converts a binary sequence string '10110...' into a float32 array (left-padded)."""
    arr = np.zeros(100, dtype=np.float32)
    # The newest brick is at the end of the string.
    # We place it at the end of the array (index 99) for consistent CNN spatial alignment.
    seq_str = seq_str[-100:]
    start_idx = 100 - len(seq_str)
    
    for i, char in enumerate(seq_str):
        if char == '1':
            arr[start_idx + i] = 1.0
        elif char == '0':
            arr[start_idx + i] = -1.0  # -1.0 for DOWN to distinguish from 0.0 padding!
            
    return arr


def build_split(split_name: str, df: pd.DataFrame, undersample: bool = False):
    if undersample:
        logger.info(f"Applying Majority Class Undersampling to {split_name}...")
        win_mask = df['y_class'] == 1
        loss_mask = df['y_class'] == 0
        n_wins = win_mask.sum()
        
        # Randomly sample losses to match wins
        losses_sampled = df[loss_mask].sample(n=n_wins, random_state=42)
        wins = df[win_mask]
        
        # Combine and sort back by time
        df = pd.concat([wins, losses_sampled]).sort_values('utc_time').reset_index(drop=True)
        logger.info(f"Balanced {split_name} split: {len(df):,} samples (50% Wins, 50% Losses)")
    else:
        logger.info(f"Building {split_name} split with {len(df):,} samples...")
    
    n_samples = len(df)
    
    # Pre-allocate massive arrays
    X_micro = np.zeros((n_samples, 10, 100, 9), dtype=np.float32)
    X_macro = np.zeros((n_samples, 10, 7), dtype=np.float32)
    X_seq = np.zeros((n_samples, 100), dtype=np.float32)
    
    y_class = np.zeros((n_samples, 1), dtype=np.float32)
    y_mag = np.zeros((n_samples, 1), dtype=np.float32)
    
    valid_count = 0
    missing = 0
    
    micro_q = deque(maxlen=10)
    macro_q = deque(maxlen=10)
    
    t_start = time.time()
    for i, row in enumerate(df.itertuples()):
        b_id = row.brick_id
        year = getattr(row, 'year', None)
        month = getattr(row, 'month', None)
        
        if year is not None and month is not None:
            month_str = f"{int(month):02d}"
            micro_path = TENSOR_DIR / f"micro_{year}_{month_str}_{b_id}.npy"
            macro_path = TENSOR_DIR / f"macro_{year}_{month_str}_{b_id}.npy"
            seq_path = TENSOR_DIR / f"seq_{year}_{month_str}_{b_id}.txt"
        elif year is not None:
            micro_path = TENSOR_DIR / f"micro_{year}_{b_id}.npy"
            macro_path = TENSOR_DIR / f"macro_{year}_{b_id}.npy"
            seq_path = TENSOR_DIR / f"seq_{year}_{b_id}.txt"
        else:
            micro_path = TENSOR_DIR / f"micro_{b_id}.npy"
            macro_path = TENSOR_DIR / f"macro_{b_id}.npy"
            seq_path = TENSOR_DIR / f"seq_{b_id}.txt"
        
        if not (micro_path.exists() and macro_path.exists() and seq_path.exists()):
            missing += 1
            continue
            
        try:
            # Load
            micro = np.load(micro_path)
            orig_macro = np.load(macro_path)
            
            # Enrich macro with regime features
            enriched_macro = np.zeros(7, dtype=np.float32)
            enriched_macro[0:3] = orig_macro
            enriched_macro[3] = row.hour_sin
            enriched_macro[4] = row.hour_cos
            enriched_macro[5] = row.brick_in_run_log
            enriched_macro[6] = row.local_wr
            
            with open(seq_path, 'r') as f:
                seq_str = f.read().strip()
                
            micro_q.append(micro)
            macro_q.append(enriched_macro)
            
            if len(micro_q) == 10:
                # Assign
                X_micro[valid_count] = np.array(micro_q)
                X_macro[valid_count] = np.array(macro_q)
                X_seq[valid_count] = sequence_to_array(seq_str)
                
                y_class[valid_count, 0] = row.y_class
                y_mag[valid_count, 0] = row.y_mag
                
                valid_count += 1
            
        except Exception as e:
            logger.error(f"Error loading brick {b_id}: {e}")
            missing += 1
            
        if (i + 1) % 10000 == 0:
            logger.info(f"  Processed {i+1}/{n_samples}...")
            
    logger.info(f"Completed {split_name}: {valid_count} valid, {missing} missing. Time: {time.time()-t_start:.1f}s")
    
    # Truncate to valid rows
    X_micro = X_micro[:valid_count]
    X_macro = X_macro[:valid_count]
    X_seq = X_seq[:valid_count]
    y_class = y_class[:valid_count]
    y_mag = y_mag[:valid_count]
    
    # Save
    np.save(OUTPUT_DIR / f"{split_name}_micro.npy", X_micro)
    np.save(OUTPUT_DIR / f"{split_name}_macro.npy", X_macro)
    np.save(OUTPUT_DIR / f"{split_name}_seq.npy", X_seq)
    np.save(OUTPUT_DIR / f"{split_name}_y_class.npy", y_class)
    np.save(OUTPUT_DIR / f"{split_name}_y_mag.npy", y_mag)
    
    logger.info(f"Saved {split_name} arrays to {OUTPUT_DIR}/")


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s"
    )
    
    logger.info("Loading all label parquets...")
    label_files = glob.glob(str(LABELS_DIR / "sim_labels_*.parquet"))
    
    if not label_files:
        logger.error(f"No label files found in {LABELS_DIR}")
        return
        
    dfs = [pd.read_parquet(f, engine='fastparquet') for f in label_files]
    df = pd.concat(dfs, ignore_index=True)
    
    logger.info(f"Total labels loaded: {len(df):,}")
    
    # Sort by timestamp
    if 'utc_time' not in df.columns:
        df['utc_time'] = pd.to_datetime(df['timestamp'], unit='ms', utc=True)
    df = df.sort_values('utc_time').reset_index(drop=True)
    
    # Mask splits
    train_mask = df['utc_time'] <= TRAIN_END
    val_mask = (df['utc_time'] > TRAIN_END) & (df['utc_time'] <= VAL_END)
    test_mask = df['utc_time'] > VAL_END
    
    # --- Compute Regime Features ---
    logger.info("Computing Regime Features...")
    
    # 1 & 2: Cyclic hour
    hour = df['utc_time'].dt.hour.values
    df['hour_sin'] = np.sin(2 * np.pi * hour / 24).astype(np.float32)
    df['hour_cos'] = np.cos(2 * np.pi * hour / 24).astype(np.float32)
    
    # 3: Brick in run (log scaled)
    direction = df['direction'].values
    N = len(df)
    brick_in_run = np.ones(N, dtype=np.float32)
    for i in range(1, N):
        if direction[i] == direction[i-1]:
            brick_in_run[i] = brick_in_run[i-1] + 1
    df['brick_in_run_log'] = np.log1p(brick_in_run).astype(np.float32)
    
    # 4: Rolling local win rate
    y = df['y_class'].values.astype(np.float32)
    local_wr = np.full(N, 0.3533, dtype=np.float32)
    for i in range(20, N):
        # We must ignore NaNs when calculating the rolling mean. 
        # y_class has NaNs when the forward outcome logic was excluded.
        window = y[i-20:i]
        valid_window = window[~np.isnan(window)]
        if len(valid_window) > 0:
            local_wr[i] = np.mean(valid_window)
    df['local_wr'] = local_wr
    
    logger.info("Regime Features computed.")
    
    df_train = df[train_mask]
    df_val = df[val_mask]
    df_test = df[test_mask]
    
    logger.info(f"Split sizes -> Train: {len(df_train):,}, Val: {len(df_val):,}, Test: {len(df_test):,}")
    
    build_split("train", df_train, undersample=False)
    build_split("val", df_val, undersample=False)
    build_split("test", df_test, undersample=False)
    
    logger.info("All tensors successfully built.")


if __name__ == "__main__":
    main()
